# -*- coding: utf-8 -*-
"""taller2analisis (2).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17ie5RWvERg_mY7umqULqMpNZGiiGSqq0
"""

import time
import numpy as np

sePudo = False

def verificarM(x,y,z,m,n,c):
  global sePudo
 # print(x,y,z,m,n,c)
  if c[m][n] != "":
    return c[m][n]
  
  if(len(z) == 0):
    sePudo = True
    return c[m][n]
 # if m == 0 and n == 0: #xddd
  #  c[m][n] = ""

  if len(x) > 0 or len(y) > 0:
    if len(x) > 0:
      if x[0] == z[0] and sePudo == False:
        c[m][n] = str(verificarM(x[1:],y,z[1:],m-1,n,c) ) + x[0]
        print(c)
    if len(y) > 0:
      if y[0] == z[0] and sePudo == False:
        c[m][n] = str(verificarM(x,y[1:],z[1:],m,n-1,c) ) + y[0]
        print(c)
  
  return c[m][n]

start_time = time.time()
x = "CASA"
y = "CARRO"
z = "CCASARROA"
sePudo = False
m = len(x)
n = len(y)
c = np.empty( (len(x)+1,len(y)+1), dtype = 'object' )
c.fill("")

cc = verificarM(x,y,z,m,n,c)
print(cc[::-1])

print("--- %s seconds ---" % (time.time() - start_time))

